### PR TITLE
Readd option to scramble pin layout when unlocking [1/2]

### PR DESCRIPTION
**Pull request by Jenna-66**
Part [2/2] is in https://github.com/ValidusOs/packages_apps_Settings

### CODE REVIEW

**Comment by Martinusbe** [comment]
think there will be an question about authorship coming

**Comment by Martinusbe** [comment]
@Martinusbe https://github.com/LineageOS/android_frameworks_base/commit/43f33322d6eab5f013f1ae8ee9d5e2d648c39dfb

**Comment by Martinusbe** [comment]
git commit --amend --author="Adnan Begovic <adnan@cyngn.com>"

**Comment by premaca** [comment]
https://github.com/ValidusOs/frameworks_base/commit/03da7c99daff7b1ef9282253dbad1177acba3c54

We got that in 8.0, you can pick that commit

**Comment by MRTHAKER** [comment]
@premaca Yeah nice feature to have tho

**Comment by Jenna-66** [comment]
It was already in Nougat: https://github.com/GZR-ValidusOS/frameworks_base/commit/2bae67aeb129df00f617b0ec4ad114760c07ca27 and https://github.com/GZR-ValidusOS/packages_apps_Settings/commit/511a46767ee1f0cae74c6c46aad7dfb1000d670d, that's wher I picked it from, except for the comment in Settings.java, which is indeed from LineageOs.
Sorry, that I did not mention it.

**Comment by Martinusbe** [comment]
yes, but it has proper authorship there too, so amend it, takes 2 seconds, you can copy paste what i posted

**Comment by Jenna-66** [comment]
Not sure if it was done correctly now (never amended a commit before).
And it took more than two seconds, even more than two minutes, because I am on ridiculous slow internet until monday (860/160 kBit) and only rare (edge) data-connections with my phone, so I had to do it via ssh on my server.
Just for the record, the amend command needs "<" and ">" around the mail-address or it does not work (at least if it is an unknown author).
If it should be done in a different way, or you use the 8.0-commit (I did not see it), feel free to close the PR's.
Nevertheless, I learned something new and that's always good.

**Comment by Martinusbe** [comment]
ah true, thought i added the <>

**Pull request merged**
